### ISSUE TITLE
Artikelbilder in den richtigen Größen erzeugen geht nimmer

### ISSUE THREAD

**Issue by phibo23** [StudentenPACK/wordpress#1]
sagt @TVLuke. Muss ich mir mal ansehen...

**Comment by phibo23** [comment]
ich hab grad mal versucht, die Ursache zu finden. Das ganze scheint seit April 2014 nicht mehr zu funktionieren. Das fällt mit dem Serverumzug zusammen. Ich vermute, da ist einfach was auf dem neuen Server falsch oder gar nicht konfiguriert. Spontan würde ich auf Schreibrechte für den upload Ordner oder fehlendes PHP Grafikmodul (http://php.net/manual/de/book.image.php) tippen. @TVLuke @xbjw @HoverBaum @NeoRaider

**Comment by NeoRaider** [comment]
Joa, da fehlte `php5-gd`, bitte jetzt nochmal probieren.

**Comment by phibo23** [comment]
thx, sieht gut aus. Danke für den schnellen Support. :)
