### ISSUE TITLE
Error, no group ID set! Check your syntax!

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#10]
Irgendwie nach dem update zur neuen version und/oder update der plugins ist jetzt "Error, no group ID set! Check your syntax!" anstelle einer rückseite zu sehen... is wohl https://wordpress.org/support/topic/error-no-group-id-set-check-your-syntax-1

**Comment by phibo23** [comment]
Einfach mal widget neu speichern hat zumindest die fehlermeldung weggemacht.

aber die haben bei der neuen Version das Fallback Feature, das wir genutzt haben, um ein standardbild anzuzeigen, wenn keine richtigen rückseiten aktiv sind, in die pro variante geschoben. arschgeigen.
<img width="1004" alt="bildschirmfoto 2015-07-19 um 13 08 21" src="https://cloud.githubusercontent.com/assets/1328782/8765668/e6535f76-2e17-11e5-8c40-4b568adac0a6.png">

Und die alten Ads kann ich auch irgendwie nicht fixen, weil der das Datum nicht übernimmt, wenn ich das ändere... (aber die waren eh alle schon abgelaufen oder?)

Anyway: Ich habe jetzt erstma fest im Widget (Design -> Widgets -> AdRotate: Rückseite) die ID 2 eingetragen. muss man dann halt manuell wieder auf 1 setzen, wenns ne echte gibt.

**Comment by TVLuke** [comment]
Not sure if best way, aber erstmal auch gut... Kann man nicht einfach die "fallback"-Werbung mit Datum von jetzt bis 2109 oder so eintragen, und dann erscheint die halt in 1/n fällen wenn es auch echte gibt?

**Comment by phibo23** [comment]
kannste gerne machen. wollte ich aber nicht selber entscheiden. man kann ja noch gewichten, dann einfach alle echten ganz hoch und die fallback ganz niedrig.

**Comment by phibo23** [comment]
achso nee.. gewichten geht auch nur noch mit pro... -.-
