### ISSUE TITLE
Emailadresse auf Redaktionsseite

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#12]
KOnnte auf die schnelle nicht rausfinden wo, aber irgendwo scheint eingestellt zu sein (oder programiert zu sein), dass nur emailadresen, de auf studentenpack.uni-luebeck.de enden ok sind... andere sorgend dafür, dass kein umschlag mehr auf der redaktionsseite http://www.studentenpack.de/index.php/die-redaktion/ angezeigt wird.

**Comment by phibo23** [comment]
Haha, das hatte ich mir schon als todo aufgeschrieben, als wir die domain gekauft haben. :D

**Comment by phibo23** [comment]
es gibt, soweit ich mich erinnere, zwei Stellen, die angepasst werden müssen (ich bin grad zu faul, das zu machen und zu testen...):
https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/archive.php#L97
https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/functions.php#L244
