### ISSUE TITLE
Neu Aufsetzen

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#14]
Ja, isn brocken, ich habe aber keine Ahnung was wir tun können. DB Dump sieht sauber aus, kein script tag, kein ?> (außer welchen von uns...)

... alles abgefuckt

**Comment by TVLuke** [comment]
evtl sollte man davor fleißig dinge geiler machen...

**Comment by phibo23** [comment]
Warum ist das neu aufsetzen issue nicht im neu aufsetzen milestone?
