### ISSUE TITLE
body in body

### ISSUE THREAD

**Issue by phibo23** [StudentenPACK/wordpress#23]
was ist da los? irgendwie nur auf artikel und kategorie seiten etc (nicht startseite). Und nur im dynamischen html, das von den dev tools angezeigt wird (also wo schon javascript drauf rumgekaut hat), nicht in dem statischen, das geladen wird.

![bildschirmfoto 2015-10-20 um 23 16 34](https://cloud.githubusercontent.com/assets/1328782/10621506/809c941e-7781-11e5-83e7-595a3d562173.png)

**Comment by TVLuke** [comment]
Hm.. ich hab auch zwei aber der obere sieht so aus

```
<body data-feedly-mini="yes">
```

und wird wohl durch mein rss-reader plugin hinzugefügt.

**Comment by TVLuke** [comment]
wenn ich rechtsclick quelltext anzeige, ist nur ein body da...

**Comment by phibo23** [comment]
wie gesagt, nur im dynamischen, den die dev tools anzeigen

**Comment by TVLuke** [comment]
evtl. auch irgend ein plugin in deinem browser?

**Comment by phibo23** [comment]
dann wäre es eins, das sowohl in ff als auch in chrome als auch in safari ist. unwahrscheinlcih.

**Comment by TVLuke** [comment]
Also bei mir is das so: <img width="1102" alt="screenshot 2015-10-20 23 36 15" src="https://cloud.githubusercontent.com/assets/1107056/10621828/746df2c6-7783-11e5-8175-00b591c5e5d1.png">

**Comment by TVLuke** [comment]
HA! Hast recht. Beide Bodys sind da von anfang an, feedly packt in das obere eine annotation

**Comment by TVLuke** [comment]
is nicht mehr oder?

**Comment by phibo23** [comment]
jo, scheint weg zu sein. vermutlich war eins der plugins schuld, die du entfernt hast.

**Comment by TVLuke** [comment]
tatsächlich wohl das weiterleitungs ding, das hat sich gern im body-tag festgesetzt...

**Comment by phibo23** [comment]
hm ja. klingt logisch.
