### ISSUE TITLE
Wie funktioniert eigentlich das Heftarchiv....

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#25]
... krieg ich grad nicht hin. Wie fügt man da ne neue Kategorie hinzu? Steht hart aufm Schlauch.

**Comment by phibo23** [comment]
äh...erinner mich dran, falls ich vergesse, das zu erklären...

**Comment by TVLuke** [comment]
erinner

**Comment by phibo23** [comment]
Äh, ja. Also. Ich versuch mal das zu rekonstruieren, ohne auszuprobieren, ob das reicht, was ich schreibe...

* Dashboard -> Beiträge -> Kategorien
* neue Unterkategorie von Heftarchiv anlegen
* ID aus der URL aufschreiben.
* in der category-heftarchiv.php 
  * hier https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/category-heftarchiv.php#L36 an gewünschter Stelle einen neuen Link einfügen mit der notierten ID
  * hier https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/category-heftarchiv.php#L79 an gewünschter Stelle einen neuen Link mit Thumbnail einfügen
* in der functions.php
  * hier https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/functions.php#L344 die neue ID hinzufügen
  * hier https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/functions.php#L363 den slug (?) der neuen Kategorie hinzufügen

**Comment by TVLuke** [comment]
ja, das hatte ich auch fast alles, aber etwas fehlt. Wenn man auf http://www.studentenpack.de/index.php/category/blog/heftarchiv/ geht ist da jedes mal ein anderes Menü oben, wenn man auf eine zeitung geht. Ich finde einfach nicht mehr raus, wie das geht... und folglich, wenn man auf camoushl geht, ist da gar kein header oben und ich weiß nicht mehr wie ich den da rein bekommen habe, weil das ja irgendwie ne kategorie und keine page ist, wo ich wüsste, wie das geht.

**Comment by phibo23** [comment]
ah ja. in dem template muss man das header dings auch noch bearbeiten https://github.com/StudentenPACK/wordpress/blob/master/wp-content/themes/StudentenPACK/_template-old-magazine-archive.php#L48
aber wenn du alles gemacht hast, was ich gelistet hab, müssten ja zumindest alle bis auf die neue kategorie auftauchen...

**Comment by TVLuke** [comment]
ok, ja, das hatte gefehlt, aber irgendwie ist es noch nicht richtig... http://www.studentenpack.de/index.php/category/blog/heftarchiv/campushl/

**Comment by TVLuke** [comment]
ah, moment if (have_posts()) :

**Comment by TVLuke** [comment]
naja, dann warte ich mal wann/ob die ihren data dump machen.

**Comment by phibo23** [comment]
:+1: hab ich auch grad gesehen. Warum ist das eigentlich aufm server weiter oben als hier auf github?
