### ISSUE TITLE
Flickr CC Lizenzen

### ISSUE THREAD

**Issue by phibo23** [StudentenPACK/wordpress#27]
Liste kann false positives enthalten, z.B. weil im Text flickr vorkommt oder es sich um eins unserer eigenen flickr bilder handelt.

- [x] http://www.studentenpack.de/index.php/2010/02/hingerichtet-im-namen-der-liebe/
- [x] http://www.studentenpack.de/index.php/2010/02/nix-los-in-lubeck/
- [x] http://www.studentenpack.de/index.php/2010/02/wer-a-sagt-muss-auch-bib-sagen/
- [x] http://www.studentenpack.de/index.php/2010/02/eine-brille-fur-blinde/
- [x] http://www.studentenpack.de/index.php/2010/04/geistliche-die-bei-der-masturbation-ihr-leben-liesen/
- [x] http://www.studentenpack.de/index.php/2010/04/digitale-mundpropaganda/
- [x] http://www.studentenpack.de/index.php/2010/06/studenten-in-der-krise/
- [x] http://www.studentenpack.de/index.php/2010/06/kein-internet-in-der-fusgangerzone/
- [x] http://www.studentenpack.de/index.php/2010/07/was-wurdet-ihr-tun/
- [x] http://www.studentenpack.de/index.php/2010/12/ohne-moos-nix-los/
- [x] http://www.studentenpack.de/index.php/2011/01/was-tun-gegen-produktpiraterie/
- [x] http://www.studentenpack.de/index.php/2011/06/lookin-for-freedom/
- [x] http://www.studentenpack.de/index.php/2011/12/frischer-wind-fur-grune-unis/
- [x] http://www.studentenpack.de/index.php/2012/04/hinter-den-wahlkabinen/
- [x] http://www.studentenpack.de/index.php/2012/04/politik-muss-wieder-offener-gestaltet-werden/
- [x] http://www.studentenpack.de/index.php/2012/05/stiften-gehen/
- [x] http://www.studentenpack.de/index.php/2012/06/wenn-eine-schutzmasnahme-zur-katastrophe-wird/
- [x] http://www.studentenpack.de/index.php/2012/07/wie-studiert-man-bier/
- [x] http://www.studentenpack.de/index.php/2012/07/quantenmechanik-fur-ahnungslose/
- [x] http://www.studentenpack.de/index.php/2013/01/flucht-in-den-frieden/
- [x] http://www.studentenpack.de/index.php/2013/01/der-kampf-ums-uberleben/
- [x] http://www.studentenpack.de/index.php/2013/01/ein-kleines-bisschen-in-die-zukunft/
- [x] http://www.studentenpack.de/index.php/2013/04/friedenstauben-und-kampfjets/
- [x] http://www.studentenpack.de/index.php/2013/04/alles-auser-fehler-machen/
- [x] http://www.studentenpack.de/index.php/2013/05/einmal-die-tasche-offnen-bitte/
- [x] http://www.studentenpack.de/index.php/2013/07/haut-ab/
- [x] http://www.studentenpack.de/index.php/2013/07/hilfe-ich-bin-nicht-arbeitslos/
- [x] http://www.studentenpack.de/index.php/2013/07/leaving-lubeck/
- [x] http://www.studentenpack.de/index.php/2013/07/von-burokratischen-hurden-und-verfehlten-zielen/
- [x] http://www.studentenpack.de/index.php/2013/11/nach-der-spritze/
- [x] http://www.studentenpack.de/index.php/2013/11/motivation-nein-danke/
- [x] http://www.studentenpack.de/index.php/2014/02/mehr-geld-fur-alle/
- [x] http://www.studentenpack.de/index.php/2014/02/von-gulden-und-talern/
- [x] http://www.studentenpack.de/index.php/2014/12/die-werwolfe-verlassen-den-dusterwald/
- [x] http://www.studentenpack.de/index.php/2015/05/grosse-namen/
- [x] http://www.studentenpack.de/index.php/2015/05/soeldner-auf-station/
- [x] http://www.studentenpack.de/index.php/2015/11/kein-einfaches-jahr/
- [x] http://www.studentenpack.de/index.php/2015/11/kein-einfaches-jahr-3/

```groovy
def file = new File("/Users/Iam/Desktop/studentenpack.wordpress.2016-02-20.xml")
def slurper = new XmlSlurper()

def content = slurper.parse(file)

def matches = content.'**'.findAll {item ->
	def text = item.encoded.text()
	text.toLowerCase().contains("flickr")
}

matches.each {
	println "- [ ] " + it.link.text()
}
```

**Comment by phibo23** [comment]
@TVLuke fyi

**Comment by TVLuke** [comment]
Das Bild unter http://www.studentenpack.de/index.php/2012/04/politik-muss-wieder-offener-gestaltet-werden/ ist nicht mehr aufzufinden, der flickr account scheint nicht mehr zu existieren. Aber es stellt sich dir Frage, ob ein Pirat einem wegen Zitierweise.... Ich find das Bild auf jeden Fall für den Artikel wichtig, wäre vielleicht was für deinen Detektivtrieb.

**Comment by phibo23** [comment]
kann es sein, dass du dein bookmarklet statt mit meiner extra eingedeutschten version mit dem original erstellt hat?

**Comment by TVLuke** [comment]
äh, das kann…

Am 21.02.2016 um 00:49 schrieb Philipp <notifications@github.com>:

**Comment by TVLuke** [comment]
ja. äh, giev mal link, ich hab den überblick verloren.

**Comment by TVLuke** [comment]
a, got it.

**Comment by phibo23** [comment]
ich vermute, das Torge Schmidt Foto ist von Enno Lenze. Hab ihm mal ne Mail geschrieben.

**Comment by TVLuke** [comment]
Hm... jetzt wo ich weiß, dass es https://www.flickr.com/photos/15267290@N03/2083329049/in/faves-studentenpack/ gibt hätte ich nicht so viele Bilder gelöscht... naja, muss mal schauen ob ich im laufe des Tages einiges restauriere (ein hoch auf die wp historie)

**Comment by phibo23** [comment]
haha, das hatte ich auch schon vergessen. Teilweise hab ich damals auch Sammlungen pro Ausgabe angelegt. Komische Ideen hatte ich damals...

**Comment by TVLuke** [comment]
voll gute ideen.

**Comment by TVLuke** [comment]
Wir gehen grad sachen durch und bei http://www.studentenpack.de/index.php/2015/11/kein-einfaches-jahr-3/ sind irgendwie bei den unteren bildern imer nur so Nico on flickr ohne den ganzen kram. Ist das richtig?

**Comment by phibo23** [comment]
oh, langer artikel. da hab ich wohl ein paar übersehen...

**Comment by TVLuke** [comment]
ok, zieh ich nach. ist das in der paginierten version entsprechend?

**Comment by phibo23** [comment]
vermutlich
