### ISSUE TITLE
Gastautoren für die ganzen Leute, die nicht in der Redaktion sind benutzen

### ISSUE THREAD

**Issue by phibo23** [StudentenPACK/wordpress#28]
Wäre das nicht viel sinnvoller? Dann müsste man nicht lauter fake Accounts anlegen, die mit ihren Dummy Login Daten ggf auch ein Security Risiko sind. Und es würden nicht lauter Emails auf dem Blogverteiler kommen (so wie heute).

@TVLuke hast du dich damit schon mal beschäftigt? Es gibt auf jeden Fall drei Gastautoren, die irgendwann mal angelegt wurden.

**Comment by TVLuke** [comment]
Ich wüsste nichtmal, dass das Feature existiert, kann man zukünftig sicher nutzen, wobei, dann is plötzlich zwei parallele systeme. zu den existierenden gibts auch "echte" accounts und die scheinen wohl auch genutzt zu werden. Hat bei mir aktuell keine prio.

**Comment by TVLuke** [comment]
Die mails bekommen glaube ich wir beide oder so... halte ich für egal.

**Comment by phibo23** [comment]
ok, wenn du die nicht angelegt hast, wer war das dann? (ich kann mich jedenfalls nicht erinnern, dass ich das war. Aber was heißt das schon. Meine Kollegen zeigen mir ca einmal im Monat Code, den erwiesenermaßen ich eingecheckt habe, an den ich mich nicht erinnern kann ^^) Jedenfalls sind zwei von den drei mit echten Autoren verknüpft, was heißt, man kann dann problemlos Leuten echte Accounts geben, wenn sie regelmäßig schreiben.

**Comment by TVLuke** [comment]
So, für die Übertragung der Texte von campus-hl nutze ich das grade. Ist gut, geht schnell. Wird weiter so gemacht. Guter Hinweis.
