### ISSUE TITLE
Kommentarspam

### ISSUE THREAD

**Issue by phibo23** [StudentenPACK/wordpress#29]
Was ist da passiert? Wir hatten doch mal ein Captcha Plugin laufen (das hier https://wordpress.org/plugins/invisible-captcha/), warum ist das weg? @TVLuke

**Comment by TVLuke** [comment]
Kann gut sein, dass das im Ramen des großen Plugins-Rausschmeißen rausgeschmissen wurde... Aber das man das merkt liegt nur daran, dass ich jetzt mal mails-erhalten aktiviert habe.

**Comment by TVLuke** [comment]
Ich hab das mal wieder installiert, jetzt wo das andere Problem gefixt scheint.
