### ISSUE TITLE
Comicleser sind laut piwik keine besucher

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#32]
Liegt wohl daran, dass das piwik plugin nicht in solche posts eingebunden ist, das müsste man mal nachziehen.

**Comment by kimbtech** [comment]
Scheint mit nach 7739c9ecd10d2d wieder zu gehen.
Eine Funktion war nicht mehr vorhanden und so wurde bei den Comics der ganze Footer (inklusive Tracking-Code) abgeschnitten.
