### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#7]
Every few times the page doesn't load, instead it returns 504. No Idea why...

**Comment by phibo23** [comment]
klingt ja mehr so nach nem allgemeinen server Problem... lässt sich auch beim Wiki reproduzieren. @NeoRaider hast du ne Ahnung, woran das liegen könnte? Geben die nginx logs was her?
![bildschirmfoto 2015-04-26 um 11 54 44](https://cloud.githubusercontent.com/assets/1328782/7336700/514ef6c2-ec0b-11e4-8c88-2c80fd7ce258.png)

**Comment by TVLuke** [comment]
Ah, ok, hatte n paar duzend mal mit wiki versucht und es passierte nichts, daher dachte ich is bestimmt wordpress... aber evtl ist es auch einfach nicht deterministisch.

**Comment by NeoRaider** [comment]
Euer PHP ist auf maximal 20 parallele Requests beschränkt (ich glaube, mehr würde auch nicht mehr sinnvoll funktionieren...), in das Limit geratet ihr manchmal. Ich vermute, dass das Wordpress es auslöst, aber das Wiki ist dann halt auch betroffen, wenn alle 20 Prozesse gerade beschäftigt sind. 

Wenn PHP häufig auf irgendwelche externen Ressourcen wartet und die CPU gar nicht beschäftigt ist, kann ich das Limit natürlich testweise mal erhöhen... Ich hab leider keine Load-Logs von dem Server aktuell.

**Comment by phibo23** [comment]
ok, dann liegt es vielleicht an dem cache plugin, das nicht mehr richtig funktioniert... habs neulich deaktiviert, aber es ist auf der startseite immernoch aktiv (ersichtlich am Kommentar ganz unten im html). Schau ich mir heute Abend nochmal an.

**Comment by phibo23** [comment]
@TVLuke kannst du das Problem noch reproduzieren? Wollte grad noch mal schauen und vor allem schauen, ob reaktivieren von dem Cacheplugin hilft, aber der Fehler kommt gar nicht mehr. Außerdem ist im Dashboard irgendwas komisch. Als ich mich vorhin eingeloggt hab, wurden ca 10 Plugin updates angezeigt, jetzt gar keins mehr... O.o

**Comment by TVLuke** [comment]
Habs die Tage nicht mehr gehabt, aber n Cache-Plugin ist sicher immer ne gute Idee. Ich habe keine PlugIns erneuert, k.A. ob jemand anderes das gemacht hat... Aber wie ich sehe gibts schon wieder ne neue Wordpress Version. Vor Juli sollte man aber nichts kritisches tun wenn das Ding läuft...

**Comment by TVLuke** [comment]
Jetzt zeigt es wieder 12 aktualisierungen an... seltsam. Ist wohl Buggy.

**Comment by phibo23** [comment]
das ist ist durch, oder?

**Comment by phibo23** [comment]
hm... Cache plugin ist an, aber Problem scheint immer noch da zu sein...

**Comment by TVLuke** [comment]
joa, könnte an https://github.com/StudentenPACK/wordpress/issues/9 liegen, das scheint ja u.a. die adresse der website woanders hinzuschicken, ich vermute von dort wird dann regelmäßig gecheckt, ob man noch infiziert ist oder so... also vieleicht löst man das problem wann man die mallware rauskriegt.

**Comment by TVLuke** [comment]
Nachdem es heute morgen gar nicht klar ging hatte ich das mal wieder an IT-Referat geschickt, vorläufig habe ich wordfence, snitch und piwik ausgeschaltet und den Cache-Zeitraum erhöht. Es werden zudem mehr Teile der Seite gecacched und ab jetzt wird auch für eingeloggete User eine gecachte Version der Seite genutzt.

Je nachdem wie die nächsten Wochen sind kann man ja auch mal schauen, ob man das eine oder andere reaktivieren kann...

**Comment by TVLuke** [comment]
Ist schon wieder seit zwei Stunden down... war auch gestern mehrfach weg. Scheint buchstäblich keinerlei unterschied zu machen, ob piwik läuft oder nicht, auch wenn das angeblich 11% der last ist. Dann mach ich den kram halt wieder an, die Daten sind ja durchaus interessant.

**Comment by TVLuke** [comment]
Wir sollten darüber nachdenken vom AStA-Server weg zu gehen. Ich glaube das 10€ Paket bei df würde uns reichen...

**Comment by phibo23** [comment]
Für den Preis kriegen wir auch nen günstigen vServer mit root Zugang... 
https://www.hosteurope.de/Server/Virtual-Server/
https://www.hetzner.de/de/hosting/produktmatrix_vserver/vserver-produktmatrix

**Comment by TVLuke** [comment]
Im Freifunk Umfeld sind Leute keine fans von hetzner... Ich hab allerdings keinerlei eigene Erfahrung.

**Comment by phibo23** [comment]
hab auch eher den Eindruck, dass deren Hardware nicht so geil ist, haben in der Firma zwei große Server von denen und beide hatten schon relativ viele Macken (einfach ausgegangen, Netzteil defekt nach wenigen Monaten, ...), aber immerhin reagieren sie schnell auf Supportanfragen. Netzteil war in ca 20 Minuten nach Email getauscht.

**Comment by NeoRaider** [comment]
Hi, diesmal gab es einen konkreten Grund für den Ausfall: Die VM mit der Datenbank hatte sich aufgehängt...

**Comment by TVLuke** [comment]
Ok. Dann schalte ich das piwik lieber doch nicht an...
