### ISSUE TITLE
Was markierta denn da

### ISSUE THREAD

**Issue by TVLuke** [StudentenPACK/wordpress#8]
würde mal sagen der Leidensdruck das zu fixen ist nahe 0 aber dokumentieren ist immer besser als nicht: Bei Multi-User-Artikeln wird beim Mouse-Over des vorletzten Autoren der "Punkt" in der letzten Zeile mit hervorgehoben.

Kann genausogut am Plugin für Multiuser liegen, das hab ich mir nicht angesehen.

![screenshot 2015-06-16 19 53 48](https://cloud.githubusercontent.com/assets/1107056/8190259/e02eaddc-1461-11e5-9dbd-ff61fe2bd314.png)

**Comment by phibo23** [comment]
hm ja. das ist tatsächlich etwas komisch. die link liste wird von dem plugin erzeugt, aber wie die elemente getrennt werden musste ich damals spezifizierte. da gibts 4 parameter: "between", "betweenLast", "before" und "after". Und das was da im php steht ergibt nicht wirklich sinn... Aber da ihr grad alle auf so einen Artikel verlinkt, werd ich da nicht jetzt dran rumbasteln (hab ich eben kurz, weil ich dachte, ich hätte die offensichtliche lösung, hatte ich aber nicht).

PS: interessant auch, dass die Reihenfolge irgendwie nicht immer alphabetisch ist...
